Controllers/CategoryController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using vkt_heroku.Data;

namespace vkt_heroku.Controllers
{
    public class CategoryController : Controller
    {
        private VktHerokuContext ctx;

        public CategoryController(VktHerokuContext context)
        {
            ctx = context;
        }

        public IActionResult Index()
        {
            var cats = ctx.Category.Include(i => i.ProductCategory).ThenInclude(f => f.Product).ToList();
            return View(cats);
        }

        public IActionResult Add()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Add([Bind("Name")]Category category)
        {
            if (ModelState.IsValid)
            {
                ctx.Category.Add(category);
                ctx.SaveChanges();
            }
            return RedirectToAction("Index");
        }
    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace vkt_heroku.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using vkt_heroku.Data;

namespace vkt_heroku.Controllers
{
    public class ProductController : Controller
    {
        private VktHerokuContext ctx;

        public ProductController(VktHerokuContext context)
        {
            ctx = context;
        }

        public IActionResult Index()
        {
            var prods = ctx.Product.ToList();
            return View(prods);
        }

        public IActionResult Add()
        {
            ViewData["Categories"] = ctx.Category.ToList();
            return View();
        }

        [HttpPost]
        public IActionResult Add([FromForm()]ProductCategory productCategory)
        {
            if (ModelState.IsValid)
            {
                ctx.Product.Add(productCategory.Product);
                if (productCategory.CategoryID != 0)
                    ctx.ProductCategory.Add(productCategory);
                ctx.SaveChanges();
            }
            return RedirectToAction("Index");
        }
    }
}

Views/Category/Add.cshtml
@model Category 
@{ ViewData["Title"] = "Add Category"; }

<form asp-action="Add" method="post">
    <div class="form-group">
        <label asp-for="Name"></label>
        <input asp-for="Name" class="form-control" placeholder="Category Name" />
        <span asp-validation-for="Name"></span>
    </div>
    <div class="form-group">
        <input type="submit" class="btn btn-primary" value="Save" />
    </div>
</form>

Views/Category/Index.cshtml
@model List<Category>
@{ ViewData["Title"] = "Categories"; }

<ul class="list-group">
    @foreach(var cat in Model){
        <li class="list-group-item">
            @cat.Name 
            <em>(@string.Join(", ", cat.ProductCategory.Select(i => i.Product.Name)))</em>
        </li>
    }
</ul>
<a asp-action="Add" class="btn btn-primary mt-4">Add Category</a>

Views/Home/Index.cshtml
@{ ViewData["Title"] = "Mainpage"; }

Views/Product/Add.cshtml
@model ProductCategory
@{ ViewData["Title"] = "Add Product"; }

<form asp-action="Add" method="post">
    <div class="form-group">
        <label asp-for="Product.Name"></label>
        <input asp-for="Product.Name" class="form-control" placeholder="Product Name" />
        <span asp-validation-for="Product.Name"></span>
    </div>
    <div class="form-group">
        <label asp-for="Product.Price"></label>
        <input asp-for="Product.Price" class="form-control" placeholder="PriceName" />
        <span asp-validation-for="Product.Price"></span>
    </div>
    <div class="form-group">
        <label>Category</label>
        <select asp-for="CategoryID" class="form-control">
            @foreach(var cat in (ViewData["Categories"] as List<Category>)){
                <option value="@cat.ID">@cat.Name</option>
            }
        </select>
    </div>
    <div class="form-group">
        <input type="submit" class="btn btn-primary" value="Save" onclick="SendForm()"/>
    </div>
</form>

Views/Product/Index.cshtml
@model List<Product>
@{ ViewData["Title"] = "Products"; }

<ul class="list-group">
    @foreach(var prod in Model){
        <li class="list-group-item"><b>@prod.Name</b> - @prod.Price TL</li>
    }
</ul>
<a asp-action="Add" class="btn btn-primary mt-4">Add Product</a>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] | VKT-HEROKU</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" asp-controller="Home" asp-action="Index">VKT-HEROKU</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" asp-controller="Product" asp-action="Index">Products</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-controller="Category" asp-action="Index">Categories</a>
                </li>
            </ul>
        </div>
    </nav>
    <div class="container mt-4">
        @RenderBody()
    </div>
    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>

</html>